const questions = {
  english: [
    { question: "What is the synonym of 'obscure'?", options: ["Clear", "Famous", "Vague", "Visible"], answer: "Vague" },
    { question: "Which of the following is a figure of speech?", options: ["Simile", "Sentence", "Grammar", "Punctuation"], answer: "Simile" },
    { question: "Choose the correct sentence:", options: ["She go to school.", "She goes to school.", "She gone to school.", "She going school."], answer: "She goes to school." },
    { question: "What is an antonym of 'benevolent'?", options: ["Kind", "Generous", "Cruel", "Loving"], answer: "Cruel" },
    { question: "What part of speech is 'quickly'?", options: ["Noun", "Verb", "Adjective", "Adverb"], answer: "Adverb" },
    { question: "Identify the main clause: 'Although it rained, we played.'", options: ["Although it rained", "It rained", "We played", "Played"], answer: "We played" },
    { question: "The opposite of 'ascend' is:", options: ["Climb", "Rise", "Lift", "Descend"], answer: "Descend" },
    { question: "He works ____ a bank.", options: ["at", "on", "in", "for"], answer: "at" },
    { question: "She sings better than ____ in class.", options: ["any girl", "any girls", "all girls", "all the girls"], answer: "any girl" },
    { question: "What is a synonym of 'elated'?", options: ["Sad", "Angry", "Happy", "Tired"], answer: "Happy" },
    { question: "Find the correct tense: 'She ____ to the store yesterday.'", options: ["go", "goes", "gone", "went"], answer: "went" },
    { question: "Which word is an interjection?", options: ["Wow", "Soon", "Quick", "Very"], answer: "Wow" },
    { question: "Choose the correct sentence:", options: ["They has arrived.", "They have arrive.", "They have arrived.", "They are arrived."], answer: "They have arrived." },
    { question: "Which is a preposition?", options: ["And", "But", "With", "Yet"], answer: "With" },
    { question: "Select the correct question tag: 'You are late, ___?'", options: ["aren’t you", "isn’t it", "don’t you", "didn’t you"], answer: "aren’t you" },
    { question: "What is the plural of 'crisis'?", options: ["crisises", "crisi", "crises", "criseses"], answer: "crises" },
    { question: "Identify the adjective: 'The clever boy passed the test.'", options: ["boy", "passed", "test", "clever"], answer: "clever" },
    { question: "Which word is a conjunction?", options: ["Always", "Although", "Awake", "Away"], answer: "Although" },
    { question: "Which is the correct possessive form?", options: ["Childs'", "Children's", "Childes'", "Childrens"], answer: "Children's" },
    { question: "Change to passive: 'He eats mangoes.'", options: ["Mangoes are eaten by him", "Mangoes eaten by him", "Mango is eaten by him", "He is eaten mangoes"], answer: "Mangoes are eaten by him" }
  ],
  math: [
    { question: "Differentiate y = x^2", options: ["2x", "x", "x^2", "1"], answer: "2x" },
    { question: "What is the solution to x² - 9 = 0?", options: ["x = 3", "x = -3", "x = ±3", "x = 9"], answer: "x = ±3" },
    { question: "Simplify: (x + 2)(x - 2)", options: ["x² - 4", "x² + 4", "x² - 2x", "x² + 2x"], answer: "x² - 4" },
    { question: "Solve: 2x + 3 = 7", options: ["x = 1", "x = 2", "x = 3", "x = 4"], answer: "x = 2" },
    { question: "What is the square root of 144?", options: ["11", "12", "13", "14"], answer: "12" },
    { question: "Convert 0.75 to a fraction", options: ["3/4", "1/2", "1/4", "2/3"], answer: "3/4" },
    { question: "Find the area of a circle of radius 7 cm (π=22/7)", options: ["154 cm²", "44 cm²", "49 cm²", "143 cm²"], answer: "154 cm²" },
    { question: "What is 10% of 200?", options: ["10", "15", "20", "25"], answer: "20" },
    { question: "Solve: x/2 = 6", options: ["x = 3", "x = 6", "x = 12", "x = 18"], answer: "x = 12" },
    { question: "Find the perimeter of a square with side 5 cm", options: ["10 cm", "15 cm", "20 cm", "25 cm"], answer: "20 cm" },
    { question: "Simplify: 2x + 3x", options: ["6x", "5x", "x", "x²"], answer: "5x" },
    { question: "What is 5 factorial (5!)?", options: ["20", "60", "100", "120"], answer: "120" },
    { question: "Find the mean of 2, 4, 6, 8", options: ["5", "6", "4", "8"], answer: "5" },
    { question: "What is ¾ × ⅔?", options: ["2/3", "3/4", "1/2", "1/6"], answer: "1/2" },
    { question: "What is the volume of a cube with side 3cm?", options: ["27cm³", "9cm³", "18cm³", "21cm³"], answer: "27cm³" },
    { question: "What is the LCM of 4 and 6?", options: ["12", "6", "8", "24"], answer: "12" },
    { question: "What is the HCF of 8 and 12?", options: ["2", "4", "6", "8"], answer: "4" },
    { question: "Simplify: 9 - 3 + 2", options: ["4", "8", "6", "10"], answer: "8" },
    { question: "What is 0.2 × 0.3?", options: ["0.5", "0.06", "0.06", "0.06"], answer: "0.06" },
    { question: "What is the probability of getting head in a fair coin toss?", options: ["0", "0.25", "0.5", "1"], answer: "0.5" }
  ],
  biology: [
    { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"], answer: "Mitochondria" },
    { question: "Which part of the plant conducts photosynthesis?", options: ["Root", "Stem", "Leaf", "Flower"], answer: "Leaf" },
    { question: "Blood is pumped by which organ?", options: ["Brain", "Liver", "Heart", "Lung"], answer: "Heart" },
    { question: "The basic unit of life is:", options: ["Atom", "Molecule", "Tissue", "Cell"], answer: "Cell" },
    { question: "Which of these is a vertebrate?", options: ["Earthworm", "Ant", "Toad", "Snail"], answer: "Toad" },
    { question: "Which blood cells fight infection?", options: ["Red", "White", "Platelets", "Plasma"], answer: "White" },
    { question: "An example of a carnivore is:", options: ["Goat", "Cow", "Lion", "Sheep"], answer: "Lion" },
    { question: "What is excretion?", options: ["Breathing", "Removal of waste", "Digestion", "Reproduction"], answer: "Removal of waste" },
    { question: "Which organ removes urea from the blood?", options: ["Liver", "Lung", "Kidney", "Intestine"], answer: "Kidney" },
    { question: "The part of the eye that controls light entry is:", options: ["Retina", "Lens", "Iris", "Cornea"], answer: "Iris" },
    { question: "What is pollination?", options: ["Growth of seed", "Transfer of pollen", "Seed dispersal", "Fertilization"], answer: "Transfer of pollen" },
    { question: "Chlorophyll is found in:", options: ["Root", "Stem", "Leaf", "Fruit"], answer: "Leaf" },
    { question: "Which cell has no nucleus?", options: ["White blood cell", "Red blood cell", "Muscle cell", "Nerve cell"], answer: "Red blood cell" },
    { question: "What is the human body’s largest organ?", options: ["Heart", "Liver", "Skin", "Lung"], answer: "Skin" },
    { question: "How many chambers does the heart have?", options: ["2", "3", "4", "5"], answer: "4" },
    { question: "The skeleton provides:", options: ["Energy", "Support", "Circulation", "Digestion"], answer: "Support" },
    { question: "Which part of the brain controls balance?", options: ["Cerebrum", "Cerebellum", "Medulla", "Thalamus"], answer: "Cerebellum" },
    { question: "Animals that give birth to young ones are:", options: ["Oviparous", "Viviparous", "Asexual", "Larval"], answer: "Viviparous" },
    { question: "The green pigment in plants is:", options: ["Haemoglobin", "Carotene", "Chlorophyll", "Xanthophyll"], answer: "Chlorophyll" },
    { question: "What does DNA stand for?", options: ["Deoxyribonucleic acid", "Dioxyribose acid", "Dextroribose acid", "Dioxynucleic acid"], answer: "Deoxyribonucleic acid" }
  ],
  chemistry: [
    { question: "Chemical symbol for gold?", options: ["Au", "Ag", "Gd", "Go"], answer: "Au" },
    { question: "Water is made up of?", options: ["H2O", "HO2", "O2H", "HHO"], answer: "H2O" },
    { question: "Acid + Base = ?", options: ["Salt + Water", "Salt + Acid", "Water", "Salt"], answer: "Salt + Water" },
    { question: "Which gas burns with a pop sound?", options: ["Hydrogen", "Oxygen", "Nitrogen", "Carbon dioxide"], answer: "Hydrogen" },
    { question: "PH scale measures?", options: ["Salt", "Acidity", "Base", "Water"], answer: "Acidity" },
    { question: "Atomic number of oxygen?", options: ["6", "7", "8", "9"], answer: "8" },
    { question: "What type of bond is NaCl?", options: ["Ionic", "Covalent", "Metallic", "Hydrogen"], answer: "Ionic" },
    { question: "Valency of carbon?", options: ["2", "4", "6", "8"], answer: "4" },
    { question: "Which is an alkali?", options: ["NaOH", "HCl", "H2SO4", "CH3COOH"], answer: "NaOH" },
    { question: "Which is not a noble gas?", options: ["Helium", "Neon", "Oxygen", "Argon"], answer: "Oxygen" },
    { question: "Electrolysis involves?", options: ["Light", "Heat", "Electricity", "Radiation"], answer: "Electricity" },
    { question: "State of matter with definite volume and shape?", options: ["Gas", "Liquid", "Solid", "Plasma"], answer: "Solid" },
    { question: "Most abundant gas in air?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], answer: "Nitrogen" },
    { question: "Boiling point of water in Celsius?", options: ["100°C", "0°C", "212°C", "90°C"], answer: "100°C" },
    { question: "What is the formula of methane?", options: ["CH4", "C2H6", "CO2", "H2"], answer: "CH4" },
    { question: "Which acid is found in the stomach?", options: ["Sulphuric", "Hydrochloric", "Nitric", "Acetic"], answer: "Hydrochloric" },
    { question: "Periodic table is arranged by?", options: ["Atomic number", "Mass number", "Valency", "Size"], answer: "Atomic number" },
    { question: "Color of phenolphthalein in acid?", options: ["Pink", "Colorless", "Red", "Blue"], answer: "Colorless" },
    { question: "H2SO4 is?", options: ["Hydrochloric", "Nitric", "Sulphuric", "Carbonic"], answer: "Sulphuric" },
    { question: "Which is a metal?", options: ["Sodium", "Carbon", "Chlorine", "Oxygen"], answer: "Sodium" }
  ]
};
